# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'attsys.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QFileDialog
from face_attendance import live, upload, identify
import os
import shutil



img = ""
name = ""
counter=0
class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(988, 590)
        self.frame = QtWidgets.QFrame(Form)
        self.frame.setGeometry(QtCore.QRect(0, 0, 991, 41))
        self.frame.setStyleSheet("background-color: rgb(0, 0, 0);\n"
"color: rgb(255, 255, 255);\n"
"")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.identifybtn = QtWidgets.QPushButton(self.frame)
        self.identifybtn.setGeometry(QtCore.QRect(890, 0, 101, 41))
        self.identifybtn.setObjectName("identifybtn")
        self.identifybtn.clicked.connect(lambda: self.stackedWidget.setCurrentWidget(self.identifypg))
       
        self.livebtn = QtWidgets.QPushButton(self.frame)
        self.livebtn.setGeometry(QtCore.QRect(790, 0, 101, 41))
        self.livebtn.setObjectName("livebtn")
        self.livebtn.clicked.connect(lambda: self.stackedWidget.setCurrentWidget(self.livepg))
         
        self.updatebtn = QtWidgets.QPushButton(self.frame)
        self.updatebtn.setGeometry(QtCore.QRect(690, 0, 101, 41))
        self.updatebtn.setObjectName("updatebtn")
        self.updatebtn.clicked.connect(lambda: self.stackedWidget.setCurrentWidget(self.updatepg))
        
        self.homebtn = QtWidgets.QPushButton(self.frame)
        self.homebtn.setGeometry(QtCore.QRect(590, 0, 101, 41))
        self.homebtn.setObjectName("homebtn")
        self.homebtn.clicked.connect(lambda: self.stackedWidget.setCurrentWidget(self.homepg))
         
        self.pushButton = QtWidgets.QPushButton(self.frame)
        self.pushButton.setGeometry(QtCore.QRect(500, 0, 81, 41))
        self.pushButton.setObjectName("pushButton")
        self.pushButton.clicked.connect(lambda: self.stackedWidget.setCurrentWidget(self.page))
        
        self.stackedWidget = QtWidgets.QStackedWidget(Form)
        self.stackedWidget.setGeometry(QtCore.QRect(0, 40, 991, 551))
        self.stackedWidget.setObjectName("stackedWidget")
        self.page = QtWidgets.QWidget()
        self.page.setObjectName("page")
        self.label_15 = QtWidgets.QLabel(self.page)
        self.label_15.setGeometry(QtCore.QRect(0, 0, 991, 551))
        self.label_15.setText("")
        self.label_15.setPixmap(QtGui.QPixmap("bg2.jpg"))
        self.label_15.setAlignment(QtCore.Qt.AlignCenter)
        self.label_15.setObjectName("label_15")
        self.label_17 = QtWidgets.QLabel(self.page)
        self.label_17.setGeometry(QtCore.QRect(40, 20, 411, 121))
        self.label_17.setObjectName("label_17")
        self.label_18 = QtWidgets.QLabel(self.page)
        self.label_18.setGeometry(QtCore.QRect(50, 210, 401, 241))
        self.label_18.setObjectName("label_18")
        self.stackedWidget.addWidget(self.page)
        self.homepg = QtWidgets.QWidget()
        self.homepg.setObjectName("homepg")
        self.label = QtWidgets.QLabel(self.homepg)
        self.label.setGeometry(QtCore.QRect(0, 0, 991, 551))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("bg2.jpg"))
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.label_5 = QtWidgets.QLabel(self.homepg)
        self.label_5.setGeometry(QtCore.QRect(40, 20, 411, 121))
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.homepg)
        self.label_6.setGeometry(QtCore.QRect(40, 170, 401, 341))
        self.label_6.setObjectName("label_6")
        self.stackedWidget.addWidget(self.homepg)
        self.updatepg = QtWidgets.QWidget()
        self.updatepg.setObjectName("updatepg")
        self.label_2 = QtWidgets.QLabel(self.updatepg)
        self.label_2.setGeometry(QtCore.QRect(0, 0, 991, 551))
        self.label_2.setText("")
        self.label_2.setPixmap(QtGui.QPixmap("bg2.jpg"))
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.frame_2 = QtWidgets.QFrame(self.updatepg)
        self.frame_2.setGeometry(QtCore.QRect(280, 170, 471, 331))
        self.frame_2.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0.473, y1:0, x2:0.502488, y2:1, stop:0 rgba(255, 255, 255, 32), stop:1 rgba(255, 255, 255, 37));\n"
"border-radius:50%")
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.label_7 = QtWidgets.QLabel(self.frame_2)
        self.label_7.setGeometry(QtCore.QRect(50, 120, 91, 41))
        self.label_7.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:0, stop:0 rgba(255, 255, 255, 0));")
        self.label_7.setObjectName("label_7")
        self.upopen = QtWidgets.QPushButton(self.frame_2)
        self.upopen.setGeometry(QtCore.QRect(170, 120, 151, 41))
        self.upopen.setStyleSheet("border-radius:20%;\n"
"background-color: rgb(0, 208, 255)")
        self.upopen.setObjectName("upopen")
        self.upopen.clicked.connect(self.open)
        
        self.lineEdit = QtWidgets.QLineEdit(self.frame_2)
        self.lineEdit.setGeometry(QtCore.QRect(170, 170, 241, 41))
        self.lineEdit.setStyleSheet("border-radius:20%;\n"
"background-color: rgb(255, 255, 255);\n"
"padding:0px 0px 0px 10px;")
        self.lineEdit.setObjectName("lineEdit")
        self.ok = QtWidgets.QPushButton(self.frame_2)
        self.ok.setGeometry(QtCore.QRect(170, 250, 161, 41))
        self.ok.setStyleSheet("border-radius:20%;\n"
"background-color: rgb(0, 208, 255);")
        self.ok.setObjectName("ok")
        self.ok.clicked.connect(self.up)
        
        self.label_8 = QtWidgets.QLabel(self.frame_2)
        self.label_8.setGeometry(QtCore.QRect(50, 170, 91, 41))
        self.label_8.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:0, stop:0 rgba(255, 255, 255, 0));")
        self.label_8.setObjectName("label_8")
        self.label_10 = QtWidgets.QLabel(self.frame_2)
        self.label_10.setGeometry(QtCore.QRect(140, 20, 161, 51))
        self.label_10.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:0, stop:0 rgba(255, 255, 255, 0));")
        self.label_10.setObjectName("label_10")
        self.label_9 = QtWidgets.QLabel(self.updatepg)
        self.label_9.setGeometry(QtCore.QRect(40, 20, 411, 121))
        self.label_9.setObjectName("label_9")
        self.stackedWidget.addWidget(self.updatepg)
        self.livepg = QtWidgets.QWidget()
        self.livepg.setObjectName("livepg")
        self.label_3 = QtWidgets.QLabel(self.livepg)
        self.label_3.setGeometry(QtCore.QRect(0, 0, 991, 551))
        self.label_3.setText("")
        self.label_3.setPixmap(QtGui.QPixmap("bg2.jpg"))
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.label_11 = QtWidgets.QLabel(self.livepg)
        self.label_11.setGeometry(QtCore.QRect(40, 20, 411, 121))
        self.label_11.setObjectName("label_11")
        self.frame_3 = QtWidgets.QFrame(self.livepg)
        self.frame_3.setGeometry(QtCore.QRect(270, 180, 451, 241))
        self.frame_3.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0.473, y1:0, x2:0.502488, y2:1, stop:0 rgba(255, 255, 255, 32), stop:1 rgba(255, 255, 255, 37));\n"
"border-radius:50%")
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.label_14 = QtWidgets.QLabel(self.frame_3)
        self.label_14.setGeometry(QtCore.QRect(100, 30, 271, 51))
        self.label_14.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:0, stop:0 rgba(255, 255, 255, 0));")
        self.label_14.setObjectName("label_14")
        self.livopen = QtWidgets.QPushButton(self.frame_3)
        self.livopen.setGeometry(QtCore.QRect(80, 150, 331, 41))
        self.livopen.setStyleSheet("border-radius:20%;\n"
"background-color: rgb(0, 208, 255)")
        self.livopen.setObjectName("livopen")
        self.livopen.clicked.connect(self.livecam)
        
        self.progressBar = QtWidgets.QProgressBar(self.livepg)
        self.progressBar.setGeometry(QtCore.QRect(250, 470, 491, 23))
        self.progressBar.setStyleSheet("QProgressBar{\n"
"border-radius:10%;\n"
"border-style:none;\n"
"text-align:center;\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, stop:0 rgba(255, 255, 255, 113), stop:1 rgba(255, 255, 255, 124));\n"
"}\n"
"QProgressBar::chunk{\n"
"border-radius:10%;\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0.494, x2:1, y2:0.455, stop:0 rgba(0, 0, 122, 255), stop:1 rgba(0, 244, 244, 255));\n"
"}")
        self.progressBar.setProperty("value", 0)
        self.progressBar.setObjectName("progressBar")
       

        self.stackedWidget.addWidget(self.livepg)
        self.identifypg = QtWidgets.QWidget()
        self.identifypg.setObjectName("identifypg")
        self.label_4 = QtWidgets.QLabel(self.identifypg)
        self.label_4.setGeometry(QtCore.QRect(0, 0, 991, 551))
        self.label_4.setText("")
        self.label_4.setPixmap(QtGui.QPixmap("bg2.jpg"))
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.label_12 = QtWidgets.QLabel(self.identifypg)
        self.label_12.setGeometry(QtCore.QRect(40, 20, 411, 121))
        self.label_12.setObjectName("label_12")
        self.frame_4 = QtWidgets.QFrame(self.identifypg)
        self.frame_4.setGeometry(QtCore.QRect(270, 190, 471, 231))
        self.frame_4.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0.473, y1:0, x2:0.502488, y2:1, stop:0 rgba(255, 255, 255, 32), stop:1 rgba(255, 255, 255, 37));\n"
"border-radius:50%")
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.label_13 = QtWidgets.QLabel(self.frame_4)
        self.label_13.setGeometry(QtCore.QRect(70, 120, 91, 41))
        self.label_13.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:0, stop:0 rgba(255, 255, 255, 0));")
        self.label_13.setObjectName("label_13")
        self.ideopen = QtWidgets.QPushButton(self.frame_4)
        self.ideopen.setGeometry(QtCore.QRect(170, 120, 231, 41))
        self.ideopen.setStyleSheet("border-radius:20%;\n"
"background-color: rgb(0, 208, 255)")
        self.ideopen.setObjectName("ideopen")
        self.ideopen.clicked.connect(self.openIde)
        
        self.label_16 = QtWidgets.QLabel(self.frame_4)
        self.label_16.setGeometry(QtCore.QRect(160, 30, 161, 51))
        self.label_16.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:0, stop:0 rgba(255, 255, 255, 0));")
        self.label_16.setObjectName("label_16")
     
       
        
       
        self.stackedWidget.addWidget(self.identifypg)
        self.retranslateUi(Form)
        self.stackedWidget.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(Form)
        
        

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.identifybtn.setText(_translate("Form", "IDENTIFY"))
        self.livebtn.setText(_translate("Form", "LIVE"))
        self.updatebtn.setText(_translate("Form", "UPDATE"))
        self.homebtn.setText(_translate("Form", "HOME"))
        self.pushButton.setText(_translate("Form", "ABOUT US"))
        self.label_17.setText(_translate("Form", "<html><head/><body><p><span style=\" font-size:24pt; font-weight:600; color:#ffffff;\">Face Recognition </span></p><p><span style=\" font-size:24pt; font-weight:600; color:#ffffff;\">Attendance System</span></p></body></html>"))
        self.label_18.setText(_translate("Form", "<html><head/><body><p><span style=\" font-size:14pt; color:#ffffff;\">FRONT END DEVELOPER </span></p><p><span style=\" font-size:12pt; color:#ffffff;\">Kratika</span></p><p><span style=\" font-size:10pt; color:#ffffff;\">email : kratikaat2000@gmail.com</span></p><p><span style=\" color:#ffffff;\"><br/></span><span style=\" font-size:14pt; color:#ffffff;\">BACK END DEVELOPER</span></p><p><span style=\" font-size:12pt; color:#ffffff;\">Dhairya Hans</span></p><p><span style=\" font-size:10pt; color:#ffffff;\">email : dhairyahans2001@gmail.com</span></p><p><span style=\" color:#000000;\"><br/></span></p><p><br/></p></body></html>"))
        self.label_5.setText(_translate("Form", "<html><head/><body><p><span style=\" font-size:24pt; font-weight:600; color:#ffffff;\">Face Recognition </span></p><p><span style=\" font-size:24pt; font-weight:600; color:#ffffff;\">Attendance System</span></p></body></html>"))
        self.label_6.setText(_translate("Form", "<html><head/><body><p><span style=\" font-size:14pt; font-weight:600; color:#ffffff;\">UPDATE </span></p><p><span style=\" font-size:11pt; color:#ffffff;\">The new entries</span></p><p><br/></p><p><span style=\" font-size:14pt; font-weight:600; color:#ffffff;\">LIVE</span></p><p><span style=\" font-size:11pt; color:#ffffff;\">Attendance feature</span></p><p><br/></p><p><span style=\" font-size:14pt; font-weight:600; color:#ffffff;\">IDENTIFY</span></p><p><span style=\" font-size:11pt; color:#ffffff;\">From the images</span></p></body></html>"))
        self.label_7.setText(_translate("Form", "<html><head/><body><p><span style=\" font-size:14pt; color:#ffffff;\">Image :</span></p></body></html>"))
        self.upopen.setText(_translate("Form", "Select"))
        self.ok.setText(_translate("Form", "OK"))
        self.label_8.setText(_translate("Form", "<html><head/><body><p><span style=\" font-size:14pt; color:#ffffff;\">Name :</span></p></body></html>"))
        self.label_10.setText(_translate("Form", "<html><head/><body><p align=\"center\"><span style=\" font-size:18pt; color:#ffffff;\">UPDATE</span></p></body></html>"))
        self.label_9.setText(_translate("Form", "<html><head/><body><p><span style=\" font-size:24pt; font-weight:600; color:#ffffff;\">Face Recognition </span></p><p><span style=\" font-size:24pt; font-weight:600; color:#ffffff;\">Attendance System</span></p></body></html>"))
        self.label_11.setText(_translate("Form", "<html><head/><body><p><span style=\" font-size:24pt; font-weight:600; color:#ffffff;\">Face Recognition </span></p><p><span style=\" font-size:24pt; font-weight:600; color:#ffffff;\">Attendance System</span></p></body></html>"))
        self.label_14.setText(_translate("Form", "<html><head/><body><p align=\"center\"><span style=\" font-size:18pt; color:#ffffff;\">LIVE ATTENDANCE</span></p></body></html>"))
        self.livopen.setText(_translate("Form", "OPEN WEBCAM"))
        self.label_12.setText(_translate("Form", "<html><head/><body><p><span style=\" font-size:24pt; font-weight:600; color:#ffffff;\">Face Recognition </span></p><p><span style=\" font-size:24pt; font-weight:600; color:#ffffff;\">Attendance System</span></p></body></html>"))
        self.label_13.setText(_translate("Form", "<html><head/><body><p><span style=\" font-size:14pt; color:#ffffff;\">Image :</span></p></body></html>"))
        self.ideopen.setText(_translate("Form", "Select"))
        self.label_16.setText(_translate("Form", "<html><head/><body><p align=\"center\"><span style=\" font-size:18pt; color:#ffffff;\">IDENTIFY</span></p></body></html>"))

        
    def open(self):
        global img
        _translate = QtCore.QCoreApplication.translate
        path = QFileDialog.getOpenFileName() 
        print(path)
        if path==('',''):
            self.label_10.setText(_translate("Form", "<html><head/><body><p align=\"center\"><span style=\" font-size:14pt; color:#ff0000;\">SELECT IMAGE!</span></p></body></html>"))
        else:
            self.upopen.setText(_translate("Form", "Selected"))
            self.label_10.setText(_translate("Form", "<html><head/><body><p align=\"center\"><span style=\" font-size:18pt; color:#ffffff;\">UPDATE</span></p></body></html>"))
        
        img = path[0]

    def up(self):
        _translate = QtCore.QCoreApplication.translate
        global img
        name=self.lineEdit.text()
            
        
        if name.strip()=='':
            self.label_10.setText(_translate("Form", "<html><head/><body><p align=\"center\"><span style=\" font-size:16pt; color:#ff0000;\">ENTER NAME!</span></p></body></html>"))
        else:
            
            self.label_10.setText(_translate("Form", "<html><head/><body><p align=\"center\"><span style=\" font-size:18pt; color:#ffffff;\">UPDATE</span></p></body></html>"))
            print(img, name)
            upload(img, name)
        
        img = ""
        name=""
        
    
    def openIde(self):
        
        path = QFileDialog.getOpenFileName() 
        print(path)
        identify(path[0])
        
    
    
    
    def livecam(self):
           self.progressBar.setProperty("value", 0)
           self.timer = QtCore.QTimer()
           self.timer.timeout.connect(self.progress1)
           self.timer.start(35)
         
    
    def progress1(self):

        global counter
        self.progressBar.setValue(counter)
        
        if counter > 100:
          self.timer.stop()

          live()
          
          counter=0

        counter += 1
        
        

        
    
        
if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())