# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'welcome.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form1(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(542, 305)
        self.progressBar = QtWidgets.QProgressBar(Form)
        self.progressBar.setGeometry(QtCore.QRect(30, 190, 491, 23))
        self.progressBar.setStyleSheet("QProgressBar{\n"
"border-radius:10%;\n"
"border-style:none;\n"
"text-align:center;\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, stop:0 rgba(255, 255, 255, 113), stop:1 rgba(255, 255, 255, 124));\n"
"}\n"
"QProgressBar::chunk{\n"
"border-radius:10%;\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0.494, x2:1, y2:0.455, stop:0 rgba(0, 0, 122, 255), stop:1 rgba(0, 244, 244, 255));\n"
"}")
        self.progressBar.setProperty("value", 24)
        self.progressBar.setObjectName("progressBar")
        self.label_17 = QtWidgets.QLabel(Form)
        self.label_17.setGeometry(QtCore.QRect(20, 10, 411, 121))
        self.label_17.setObjectName("label_17")
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setGeometry(QtCore.QRect(250, 220, 131, 20))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(Form)
        self.label_3.setGeometry(QtCore.QRect(500, 280, 41, 20))
        self.label_3.setObjectName("label_3")
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(0, -10, 551, 321))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("bg1.jpg"))
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.label.raise_()
        self.progressBar.raise_()
        self.label_17.raise_()
        self.label_2.raise_()
        self.label_3.raise_()

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label_17.setText(_translate("Form", "<html><head/><body><p><span style=\" font-size:24pt; font-weight:600; color:#ffffff;\">Face Recognition </span></p><p><span style=\" font-size:24pt; font-weight:600; color:#ffffff;\">Attendance System</span></p></body></html>"))
        self.label_2.setText(_translate("Form", "<html><head/><body><p><span style=\" font-size:10pt; color:#ffffff;\">loading.....</span></p></body></html>"))
        self.label_3.setText(_translate("Form", "<html><head/><body><p align=\"right\"><span style=\" color:#ffffff;\">@KD </span></p></body></html>"))

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form1()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())